### PR TITLE
colors more distinct, if's without (), endresult stays visible for 2  secs

### PR DESCRIPTION
**Pull request by JdeH**
Some slight alterations.
Feel free to throw away and follow your own line!
Only memory.py is important, the rest of the files are compilation results.

Jacques

### CODE REVIEW

**Comment by artyprog** [comment]
Thank you Jacques,

You are  much more competant  than me :-) , I will your apply your
modifications.

Regards

2016-06-28 12:11 GMT+02:00 Jacques de Hooge notifications@github.com:

**Comment by artyprog** [comment]
I am not able to merge it automatically.
I  must say I am not very familiar with git command. 
If you have an advise...

**Comment by artyprog** [comment]
...and I really like your modifications :-)

2016-06-28 13:57 GMT+02:00 Salvatore DI DIO salvatore.didio@gmail.com:

**Comment by JdeH** [comment]
Merging always gives me headaches too, so I don not really have a good advice for you there, sorry.
Why not just cut and paste the parts that you like into your own code...

**Comment by artyprog** [comment]
The simpler the better :-)

2016-06-28 15:32 GMT+02:00 Jacques de Hooge notifications@github.com:

**Comment by JdeH** [comment]
Right

**Pull request closed without merging**
